### ISSUE TITLE
signal only works in main thread

### ISSUE THREAD

**Issue by kmkwon94** [facebookresearch/TransCoder#11]
I got this error 
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/TransCoder/server.py", line 115, in translate
    result = run_model_1(input_string, check_source_value, check_target_value, userDirName)
  File "/TransCoder/server.py", line 145, in run_model_1
    output = translator1.translate(input_dir, src_lang, tgt_lang)
  File "/TransCoder/translate.py", line 115, in translate
    tokens = [t for t in tokenizer(input_file)]
  File "/TransCoder/preprocessing/src/code_tokenizer.py", line 338, in tokenize_cpp
    tokens_and_types = get_cpp_tokens_and_types(s)
  File "/TransCoder/preprocessing/src/timeout.py", line 32, in wrapper
    signal.SIGALRM, partial(_handle_timeout, 0))
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread`

I made a flask server, then I uploaded cpp file and converted to java what's the problem?

**Comment by kmkwon94** [comment]
I solove this issue by deleting '@timeout(10)' above of tokenize_cpp(s) methods 
I have no idea this solution is correct.
anyway I closed this issue
