### ISSUE TITLE
"None option is not viable in processing.py"

### ISSUE THREAD

**Issue by LawrenceMMStewart** [facebookresearch/TransCoder#17]
Hello, 

In the readme it details that one can select the third language as `None`  during the processing pipeline. However this option does not work: Running the pipeline on your test data with `lang1 = python`, `lang2=cpp`, `lang3=None` returns:

```
Traceback (most recent call last):
  File "/private/home/lawrencestewart/.conda/envs/transcoder/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/private/home/lawrencestewart/.conda/envs/transcoder/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/home/lawrencestewart/DeepTyper/preprocessing/preprocess.py", line 154, in <module>
    lang3=args.lang3, size_gb=args.bpe_train_size, test_size=args.test_size)
  File "/private/home/lawrencestewart/DeepTyper/preprocessing/preprocess.py", line 51, in preprocess
    test_size=test_size, lang3=lang3)
  File "/private/home/lawrencestewart/DeepTyper/preprocessing/src/dataset.py", line 148, in __init__
    self.lang1 = Language(root, lang1)
  File "/private/home/lawrencestewart/DeepTyper/preprocessing/src/dataset.py", line 25, in __init__
    ), f"failed to initalize Language {self.l}, there is no directory {str(self.folder)}"
AttributeError: 'Language' object has no attribute 'l'
```

Not high priority but I thought it would be of interest! Cheers :)

**Comment by orazheng** [comment]
@LawrenceMMStewart Did you solved this problem? Maybe you can try: 
`python -m preprocessing.preprocess '/content/TransCoder/data/test_dataset' --lang1 cpp --lang2 python --keep_comments True --bpe_train_size 0 --test_size 10 --local True`
just leave lang3 by default.

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue.
