### ISSUE TITLE
OSError: /usr/lib/llvm-7/lib//libclang-11.so

### ISSUE THREAD

**Issue by surya1011** [facebookresearch/TransCoder#25]
I am trying to setup the code in google cloud VM. I have installed all the packages as mentioned in the dependencies page and I have installed the latest cython version(0.29.21). I am getting the below error when I try to run the translate.py file
Command ran -
```
python translate.py --src_lang cpp --tgt_lang python --model_path model_2.pth < input_code.cpp
```

Error -
```
Traceback (most recent call last):
  File "/home/sudheerbabu_pakanati/transcoder/lib/python3.7/site-packages/clang/cindex.py", line 4173, in get_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/llvm-7/lib//libclang-11.so: cannot open shared object file: No such file or directory
```

**Comment by QuentinN42** [comment]
According to @brozi first commit if `libclang-11.so` isn't located on `/usr/lib/llvm-7/lib/` you must modify `./preprocessing/src/code_tokenizer.py` at line `24` from
```python
clang.cindex.Config.set_library_path('/usr/lib/llvm-7/lib/')
```
To :
```python
clang.cindex.Config.set_library_path("/path/to/lib/clang/libclang-11.so")
```

**Comment by brozi** [comment]
I don't know if you managed to fix your problem but you can also try to downgrade the clang package to version 6.0.0.2 and then locate libclang.so if it is not in `/usr/lib/llvm-7/lib/`
```
pip install clang==6.0.0.2
```

**Comment by tqblack** [comment]
Tried both methods, still throwing this error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 4129, in get_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /path/to/lib/clang/libclang-11.so/libclang.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TransCoder/translate.py", line 24, in <module>
    import preprocessing.src.code_tokenizer as code_tokenizer
  File "/content/TransCoder/preprocessing/src/code_tokenizer.py", line 29, in <module>
    idx = clang.cindex.Index.create()
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 2666, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 198, in __get__
    value = self.wrapped(instance)
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 4103, in lib
    lib = self.get_cindex_library()
  File "/usr/local/lib/python3.6/dist-packages/clang/cindex.py", line 4134, in get_cindex_library
    raise LibclangError(msg)
clang.cindex.LibclangError: /path/to/lib/clang/libclang-11.so/libclang.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().`

**Comment by tqblack** [comment]
Definitely was a user error on the above comment, but to fix the clang error all I did was open the code_tokenizer.py file and replace line 24 with this, save and exit.  --> clang.cindex.Config.set_library_file('/usr/lib/x86_64-linux-gnu/libclang-6.0.so.1') 

This worked for me and I was able to get some output.

**Comment by AheadYoung** [comment]
line 24 
clang.cindex.Config.set_library_file('/usr/lib/x86_64-linux-gnu/libclang-6.0.so.1')
line 30 
# idx = clang.cindex.Index.create()

**Comment by malachaux** [comment]
This repo is now deprecated. Please now refer to our new repository https://github.com/facebookresearch/CodeGen, which solves this issue. Does not use clang anymore !
