### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by peterzsj6** [facebookresearch/TransCoder#38]
After following the instruction for downloading GitHub data from google big query, I encounter the following issue while running the pipeline. The exception is raised, but the pipeline still runs for a while before it stopped with no other error. 
I am kinda a noob in python, I tried to print out  s, and err.value in the raw_decoder function, but nothing was printed.
I am using python 3.7.

Has anyone else encountered the same issue?

root@56c7f8eec716:/ghome/yuy/transcoder/TransCoder# . preprocess_test.sh
cpp: process ...
java: process ...
python: process ...
cpp: tokenizing 189 json files ...
s= repo_name,ref,path,copies,content
 err.value= 0
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/python-3.7.5/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/src/dataset.py", line 71, in process
    self.process_json_and_tok(keep_comments, tok_executor)
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/src/dataset.py", line 36, in process_json_and_tok
    job.result()
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/src/utils.py", line 278, in result
    self._result = self.func(*self.args, **self.kwargs)
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/src/utils.py", line 81, in process_and_tokenize_json_file
    x = json.loads(line)
  File "/usr/local/python-3.7.5/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python-3.7.5/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python-3.7.5/lib/python3.7/json/decoder.py", line 358, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python-3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/preprocess.py", line 119, in <module>
    lang3=args.lang3, size_gb=args.bpe_train_size, test_size=args.test_size)
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/preprocess.py", line 65, in preprocess
    lang_executor=mp_executor, tok_executor=cluster_ex1, split_executor=cluster_ex2)
  File "/ghome/yuy/transcoder/TransCoder/preprocessing/src/dataset.py", line 165, in process_languages
    self.sizes[lang.l] = jobs[i].result()
  File "/usr/local/python-3.7.5/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/python-3.7.5/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by peterzsj6** [comment]
NVM about it, I didn't use NOT NULL in the query for the google big table.
