### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by ShahzaibJak** [facebookresearch/TransCoder#52]
Traceback (most recent call last):
  File "TransCoder/translate.py", line 179, in <module>
    input, lang1=params.src_lang, lang2=params.tgt_lang, beam_size=params.beam_size)
  File "TransCoder/translate.py", line 138, in translate
    min(self.reloaded_params.max_len, 3 * len1.max().item() + 10)),
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by SavinashSinnasamy** [comment]
**A CUDA Error: Device-Side Assert Triggered** can either be caused by an inconsistency between the number of labels and output units or an incorrect input for a loss function.
To solve it, you need to make sure your output units match the number of classes and that your output layer returns values in the range of the loss function (criterion) that you chose.
